//! Generated by ZPM tools/generate_sb0_contract.py; do not edit.
//! Source SHA-256: 2588397b8e476748d7b4e90f129a53a1bcad431485f77a1831726fd9dae0eaff

pub const CONTRACT_VERSION = "1.0.0";
pub const APP_ID = "tech.sb0.sample";
pub const SDK_REQUIREMENT = "^1.0.0";
pub const SOURCE_SHA256 = "2588397b8e476748d7b4e90f129a53a1bcad431485f77a1831726fd9dae0eaff";
pub const MAX_REQUEST_BODY: usize = 4096;

pub const Capabilities = struct {
    pub const network = true;
    pub const storage = true;
};

pub const Method = enum { GET, POST, PUT, DELETE, PATCH };
pub const Route = struct {
    method: Method,
    path: []const u8,
    max_body: usize,
};

pub const routes = [_]Route{
    .{ .method = .GET, .path = "/health", .max_body = 0 },
    .{ .method = .POST, .path = "/v1/items", .max_body = 4096 },
};
