#!/usr/bin/env python3
"""Generate a deterministic Sig module from an SB0 application contract."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path


METHODS = {"GET", "POST", "PUT", "DELETE", "PATCH"}
SEMVER = re.compile(
    r"^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)"
    r"(?:-[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?"
    r"(?:\+[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?$"
)


def quoted(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def render(source: Path) -> str:
    raw = source.read_bytes()
    document = json.loads(raw)
    version = document["version"]
    app_id = document["app_id"]
    sdk_requirement = document["sdk_requirement"]
    if not isinstance(version, str) or SEMVER.fullmatch(version) is None:
        raise ValueError("contract version must be SemVer (major.minor.patch)")
    if not isinstance(app_id, str) or not app_id:
        raise ValueError("contract app_id must be a non-empty string")
    if not isinstance(sdk_requirement, str) or not sdk_requirement:
        raise ValueError("contract sdk_requirement must be a non-empty string")

    max_request_body = int(document["max_request_body"])
    if max_request_body < 0:
        raise ValueError("max_request_body must be non-negative")
    capabilities = document["capabilities"]
    if not isinstance(capabilities, dict):
        raise ValueError("contract capabilities must be an object")

    routes = document["routes"]
    if not isinstance(routes, list) or not routes:
        raise ValueError("contract routes must be a non-empty array")

    lines = [
        "//! Generated by ZPM tools/generate_sb0_contract.py; do not edit.",
        f"//! Source SHA-256: {hashlib.sha256(raw).hexdigest()}",
        "",
        f"pub const CONTRACT_VERSION = {quoted(version)};",
        f"pub const APP_ID = {quoted(app_id)};",
        f"pub const SDK_REQUIREMENT = {quoted(sdk_requirement)};",
        f"pub const SOURCE_SHA256 = {quoted(hashlib.sha256(raw).hexdigest())};",
        f"pub const MAX_REQUEST_BODY: usize = {max_request_body};",
        "",
        "pub const Capabilities = struct {",
        f"    pub const network = {str(bool(capabilities.get('network'))).lower()};",
        f"    pub const storage = {str(bool(capabilities.get('storage'))).lower()};",
        "};",
        "",
        "pub const Method = enum { GET, POST, PUT, DELETE, PATCH };",
        "pub const Route = struct {",
        "    method: Method,",
        "    path: []const u8,",
        "    max_body: usize,",
        "};",
        "",
        "pub const routes = [_]Route{",
    ]
    route_keys: set[tuple[str, str]] = set()
    for route in routes:
        method = route["method"].upper()
        if method not in METHODS:
            raise ValueError(f"unsupported method: {method}")
        path = route["path"]
        if not isinstance(path, str) or not path.startswith("/"):
            raise ValueError("route path must start with '/'")
        route_key = (method, path)
        if route_key in route_keys:
            raise ValueError(f"duplicate route: {method} {path}")
        route_keys.add(route_key)
        max_body = int(route.get("max_body", 0))
        if max_body < 0 or max_body > max_request_body:
            raise ValueError(f"invalid max_body for {path}")
        lines.append(
            f"    .{{ .method = .{method}, .path = {quoted(path)}, .max_body = {max_body} }},"
        )
    lines.extend(["};", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = render(args.source)
    if args.check:
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != generated:
            print(f"stale generated contract: {args.output}")
            return 1
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generated, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
